# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Hershic
tagline:          The New Age Sysiphus
url:              http://getpoole.com
paginate:         1
baseurl:          /
author:           Eric Crosson
  name:
  url:            https://github.com/EricCrosson
  email:          eric.s.crosson@utexas.edu

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/hershic/hershic.github.io
