# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Hershic
tagline:          The New Age Sisyphus
url:              http://hershic.github.io
paginate:         1
baseurl:          /
author:           Eric Crosson
  name:
  url:            https://github.com/EricCrosson
  email:          eric.s.crosson@utexas.edu

# Custom vars
version:          1.0.0
github:           https://github.com/hershic
  repo:           https://github.com/hershic/hershic.github.io
